#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    config:
      import-check:
        enabled: false
#  cloud:
#    gateway:
#      routes:
#        - id:  order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/orders/**
#
#        - id:  payment-service
#          uri: lb://payment-service
#          predicates:s
#            - Path=/payment/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/inCaseOfFailureUseThis

server:
  port: 9191