#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone:  http://localhost:8761/eureka
#  instance:
#    hostname: localhost

spring:
  application:
    name: order-service
  cloud:
    config:
      import-check:
        enabled: false